#!/usr/bin/env python3
"""Regenerate the root README.md from the problem folders.

Each problem lives in <topic>/<number>-<slug>/ and its README.md starts with:

    # <number>. <Title>

    **Source:** <url> | **Topic:** <topic> | **Difficulty:** <Easy|Medium|Hard> | **Solved:** YYYY-MM-DD
"""
import datetime
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DIFFICULTIES = ("Easy", "Medium", "Hard")
# Total problems on LeetCode by difficulty; bump these occasionally.
LEETCODE_TOTALS = {"Easy": 880, "Medium": 1850, "Hard": 830}
RECENT_COUNT = 10

TITLE_RE = re.compile(r"^#\s*(\d+)\.\s*(.+?)\s*$", re.M)
FIELD_RE = re.compile(r"\*\*(\w+):\*\*\s*([^|\n]+?)\s*(?:\||$)", re.M)


def load_problems():
    problems = []
    for readme in sorted(ROOT.glob("*/*/README.md")):
        folder = readme.parent
        if folder.parts[-2].startswith(".") or folder.parts[-2] == "scripts":
            continue
        text = readme.read_text()
        title = TITLE_RE.search(text)
        if not title:
            continue
        fields = dict(FIELD_RE.findall(text))
        problems.append({
            "number": int(title.group(1)),
            "title": title.group(2),
            "url": fields.get("Source", ""),
            "topic": fields.get("Topic", folder.parts[-2]),
            "difficulty": fields.get("Difficulty", "?").capitalize(),
            "date": fields.get("Solved", ""),
            "path": folder.relative_to(ROOT).as_posix(),
        })
    return problems


def pct(a, b):
    return f"{100 * a / b:.1f}%" if b else "0.0%"


def badge(difficulty):
    return {"Easy": "🟢 Easy", "Medium": "🟡 Medium", "Hard": "🔴 Hard"}.get(difficulty, difficulty)


def build(problems):
    total = len(problems)
    by_diff = Counter(p["difficulty"] for p in problems)
    by_topic = Counter(p["topic"] for p in problems)
    dates = sorted({p["date"] for p in problems if p["date"]})
    today = datetime.date.today().isoformat()

    out = [
        "# Java Solutions — LeetCode",
        "",
        "My accepted LeetCode solutions in Java, organized by topic, with the approach and complexity for each problem.",
        "",
        "## Progress",
        "| Metric | Value |",
        "|---|---|",
        f"| Problems solved | {total} |",
        f"| Active days | {len(dates)} |",
        f"| Last updated | {today} |",
        "",
        "## Difficulty-wise progress",
        "| Difficulty | Solved | Progress |",
        "|---|---|---|",
    ]
    for d in DIFFICULTIES:
        out.append(f"| {badge(d)} | {by_diff[d]} / {LEETCODE_TOTALS[d]} | {pct(by_diff[d], LEETCODE_TOTALS[d])} |")

    out += ["", "## Topic-wise progress", "| Topic | Solved |", "|---|---|"]
    for topic, count in sorted(by_topic.items(), key=lambda kv: (-kv[1], kv[0])):
        out.append(f"| {topic} | {count} |")

    recent = sorted(problems, key=lambda p: (p["date"], p["number"]), reverse=True)[:RECENT_COUNT]
    out += ["", "## Recent activity", "| Date | Problem | Topic | Difficulty |", "|---|---|---|---|"]
    for p in recent:
        out.append(f"| {p['date']} | [{p['number']}. {p['title']}](./{p['path']}/) | {p['topic']} | {badge(p['difficulty'])} |")

    out += ["", "## All problems", "| # | Problem | Topic | Difficulty | LeetCode |", "|---|---|---|---|---|"]
    for p in sorted(problems, key=lambda p: p["number"]):
        link = f"[link]({p['url']})" if p["url"] else ""
        out.append(f"| {p['number']} | [{p['title']}](./{p['path']}/) | {p['topic']} | {badge(p['difficulty'])} | {link} |")

    out += [
        "",
        "## Adding a problem",
        "```bash",
        'python3 scripts/new_problem.py 1 "Two Sum" arrays Easy',
        "```",
        "This creates `arrays/1-two-sum/` with a `README.md` and `Solution.java`. Paste your solution, fill in the approach,",
        "then commit and push. The README tables above are regenerated by `scripts/update_readme.py`",
        "(the GitHub Action also runs it on every push).",
        "",
    ]
    return "\n".join(out)


def main():
    (ROOT / "README.md").write_text(build(load_problems()))


if __name__ == "__main__":
    main()
